// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUcfBqvyOd-06BwVZ3aB-6DiFK2S7Pg9Y',
    appId: '1:782486650936:web:6bfbfe32304f44d74e26cd',
    messagingSenderId: '782486650936',
    projectId: 'cineverse-c08c8',
    authDomain: 'cineverse-c08c8.firebaseapp.com',
    storageBucket: 'cineverse-c08c8.firebasestorage.app',
    measurementId: 'G-CC90Z1FZ4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXG9DK91FK3sXbnUebS2djuRD5VpP0NhQ',
    appId: '1:782486650936:android:ad4071dc2f95be784e26cd',
    messagingSenderId: '782486650936',
    projectId: 'cineverse-c08c8',
    storageBucket: 'cineverse-c08c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNHXwrbJheJL8cVk7Gqp5_gV4GwNTobjo',
    appId: '1:782486650936:ios:c449d738a2dc7bbc4e26cd',
    messagingSenderId: '782486650936',
    projectId: 'cineverse-c08c8',
    storageBucket: 'cineverse-c08c8.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNHXwrbJheJL8cVk7Gqp5_gV4GwNTobjo',
    appId: '1:782486650936:ios:c449d738a2dc7bbc4e26cd',
    messagingSenderId: '782486650936',
    projectId: 'cineverse-c08c8',
    storageBucket: 'cineverse-c08c8.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUcfBqvyOd-06BwVZ3aB-6DiFK2S7Pg9Y',
    appId: '1:782486650936:web:a7c999f02d13afc74e26cd',
    messagingSenderId: '782486650936',
    projectId: 'cineverse-c08c8',
    authDomain: 'cineverse-c08c8.firebaseapp.com',
    storageBucket: 'cineverse-c08c8.firebasestorage.app',
    measurementId: 'G-CTXQ8C2ZSK',
  );
}
